name: Validate
on: [push, workflow_call, pull_request]

jobs:
  verify:
    name: Verify Code
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - run: pnpm check
      - run: pnpm test
      - run: node bin/publish-extension.cjs --help

  e2e-test:
    name: E2E Publish Test
    runs-on: ubuntu-22.04
    # If PR is from a fork, secrets aren't available, so skip this job.
    if: github.event.pull_request.head.repo.fork != true
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: ./scripts/dev.sh all
        env:
          CHROME_EXTENSION_ID: ${{ secrets.TEST_CHROME_EXTENSION_ID }}
          CHROME_CLIENT_ID: ${{ secrets.TEST_CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.TEST_CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.TEST_CHROME_REFRESH_TOKEN }}
          CHROME_SKIP_SUBMIT_REVIEW: 'true'
          CHROME_PUBLISH_TARGET: trustedTesters
          FIREFOX_EXTENSION_ID: ${{ secrets.TEST_FIREFOX_EXTENSION_ID }}
          FIREFOX_JWT_ISSUER: ${{ secrets.TEST_FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.TEST_FIREFOX_JWT_SECRET }}
          FIREFOX_CHANNEL: unlisted
          EDGE_PRODUCT_ID: ${{ secrets.TEST_EDGE_PRODUCT_ID }}
          EDGE_CLIENT_ID: ${{ secrets.TEST_EDGE_CLIENT_ID }}
          EDGE_API_KEY: ${{ secrets.TEST_EDGE_API_KEY }}
          EDGE_SKIP_SUBMIT_REVIEW: 'true'
